project_id = "nextum-lms"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "core", "content", "learning", "lms", "ai", "data", "reporting", "audit"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
