-- Remote history marker: lms_profile_core_sync.
-- The resulting end-state schema is consolidated into the clean 0001 baseline.
-- Intentionally no-op so a fresh local reset does not recreate retired legacy sync objects.
